### PR TITLE
Removing unnecessary file inclusion and using Magento's built in meth…

### PR DESCRIPTION
**Pull request by edward-simpson**
…ods to load required models and blocks

Magento isn't meant to be filled with `include_once`, I have gone through the module, fixed class name declarations to be compatible with Magento, and modified functions to use Magento's `Mage::getMethod()`, `Mage::getBlockSingleton()` where necessary

### CODE REVIEW

**Comment by dmitridr** [comment]
Hello,

Thanks for the pull request, but I'm not sure we could accept it. Would you mind going into detail why these includes you have removed are not necessary? We found in the past that the plugin breaks and causes server 500 if compilation mode is enabled without these statements that you have removed being present.

**Comment by dmitridr** [comment]
I took a second look and it seems reasonable that we can accept this if we test it thoroughly, though I'm still worried it will break compilation mode. Please accept the CLA and we can test this ourselves, though it would be helpful to know if you've tried testing it on compilation mode also.

**Comment by edward-simpson** [comment]
Hi Dmitri,

Magento autoloads all classes declared in the etc/config.xml file (even if you just declare `Mage_Core_Model` it will autoload everything else under `Mage_Core_Model_*`, then using Mage::getModel, Mage::getSingleton, Mage::getBlockSingleton, it will load the desired class.

I've done a bit of testing my end but let me know if you run into any issues and I'll fix what I can!

I've already completed the CLA so my account should be on your system

Kind regards,


Edward

**Comment by dmitridr** [comment]
Hi Edward, 

I wanted to give you an update : we are looking at this change and testing it locally to make sure everything is fine on different versions, we will probably merge it sometime next week, but we will send out v2.6.1 with more critical fixes first, including the fix in your other PR.

Thanks for sending us this! I think this makes the code a lot nicer, and we weren't aware of this kind of approach, which is why we used includes.

If you see further problems similar to this, we'd love to hear about it (either via PR or otherwise).

Cheers,
Dmitri

**Comment by edward-simpson** [comment]
Hi Dmitiri,

No problem at all, happy to help, send me a message any time if you want me to take a look at anything!

Kind regards,


Edward

**Comment by edward-simpson** [comment]
Hi Dmitri,

What's the latest timeline on this being merged?

Kind regards,


Edward

**Comment by dmitridr** [comment]
Rebased.

**Comment by dmitridr** [comment]
Thanks for your patience @edward-simpson, we have merged this and we'll finally add this in the next version. I did discover another bug, `common.php` needed to be renamed to `Common.php` for the changes to work properly. 

Strange how it worked for you, but on mine this was needed! Thanks again for the pull request.

Cheers, Dmitri.

**Pull request closed without merging**
