### PR TITLE
fix #19

### LINKED ISSUE #19: Support catalogues containing multibyte characters
This Magento extension currently makes use of string manipulation functions that are not multibyte safe.  This means that the character limit enforcement in `FBProductFeed::buildProductAttrText`, for example, can end up producing invalid UTF-8 output.

I'm afraid I can't provide a diff for the work that we've had to do to get this to work due to the level of customisation that we've made to the file already, but an easy win would be to search and replace `substr` and `strlen` in that file and replace with their multi-byte counterparts - `mb_substr` and `mb_strlen`.

### PR DESCRIPTION
**Pull request by mpalasis**
fix https://github.com/facebookincubator/facebook-for-magento/issues/19
replace strlen and substr with mb_strlen and mb_substr respectively
credit: punkstar

this bug may also cause: https://github.com/facebookincubator/facebook-for-magento/issues/42

### CODE REVIEW

**Comment by mpalasis** [comment]
hmmm no, too much of a headache to bother even reading that, just cancel the Pull request... 
compare: https://raw.githubusercontent.com/fbsamples/audience-network-support/master/LICENSE
to: https://code.facebook.com/cla

yea, I saw it too.

**Comment by dmitridr** [comment]
Hey, thanks for this! This is great, but if you can't sign the CLA we unfortunately can't give you the credit for this. Though we'll still use it cause it's a great fix.

**Comment by dmitridr** [comment]
https://github.com/facebookincubator/facebook-for-magento/commit/0149373994f704486cc349bf44879c6bf3d434ea adds this.

**Comment by mpalasis** [comment]
no problem, was just too cross-eyed at the moment to decypher the legalese (it was 5am... and I'm not a layer)

**Pull request closed without merging**
