### PR TITLE
Fixing FBProductFeed for when no ->stock is set

### PR DESCRIPTION
**Pull request by edward-simpson**
This was erroring on install so committed this quick addition

### CODE REVIEW

**Comment by dmitridr** [comment]
Hey, 
@edward-simpson  Good catch! Please accept the CLA and we can merge this. It's just a brief document saying we can use your fix and you grant us full permission to use your fix, and your fix doesn't include any 3rd party code that is incompatible with the project license.

**Comment by edward-simpson** [comment]
Hi Dmitiri,

I've already accepted the CLA so this should all be fine

Kind regards,


Edward

**Comment by dmitridr** [comment]
Hi @edward-simpson unfortunately we aren't allowed to merge this unless you sign it using the link above.  Would you mind signing it again?  or if you've signed it using that link, could you please confirm that? I will try to figure out what is wrong with our open source system by asking our open source team.

**Comment by edward-simpson** [comment]
@dmitridr I've gone through the CLA process again

**Comment by dmitridr** [comment]
Thanks, we'll merge this asap!

**Pull request closed without merging**
